### PR TITLE
Add a `CONTRIBUTING.md` file

### PR DESCRIPTION
**Pull request by Panquesito7**
...content for how to contribute in `README.md`. GitHub will also detect this file is used for our contributing guidelines.

**Description**

- Add a `CONTRIBUTING.md` file.
  - Provides the same content for how to contribute in the `README.md` file. GitHub will also detect this file is used for our contributing guidelines.

**Notes for Reviewers:**

Ready to merge.

**[Signed commits](https://github.com/DevsTrons/hello-world/blob/master/CONTRIBUTING.md)**

- [x] Yes, I am a Member of **DEVSTRONS'**

**Discord id** (eg: Panquesito7#3723):

### CODE REVIEW

**Comment by amino19** [comment]
@Panquesito7: Actually, we have some dynamic plan to generate CONTRIBUTING.md file, as @vsnthdev said earlier.
Try to be active/participate more in discussions, & remember before making a PR acknowledge us at [#project-plan](https://discord.com/channels/857641826953854987/867815462535823360/886154421178859521).

**Comment by vsnthdev** [comment]
### 📖 The Plan

We'll have a well-documented, example markdown file for contributing a language that will be dynamically injected into `CONTRIBUTING.md`. This `example.md` will be excluded from rendering in the frontend and everything will be documented guiding a new user on contributing a new programming language.

We're also willing to have a list of contributable programming languages in `README.md` to let people directly contribute without having to look for a language...

**Comment by alphaX86** [comment]
@amino19 is this PR still on hold?

**Comment by amino19** [comment]
> @amino19 is this PR still on hold?

Yes, we want to produce CONTRIBUTING.md dynamically!

**Pull request merged**
