### PR TITLE
Add site files with blank data

### PR DESCRIPTION
**Pull request by alphaX86**
Signed-off-by: Aadhitya A <aadhitya864@gmail.com>

Description:
This PR adds new Jekyll files and a Makefile to serve site locally

**Note**:
Test the changes and then comment. Also, instead of files at `Lang` instructions may need to be placed at `_posts` folder from now on. Just review and comment :)

### CODE REVIEW

**Comment by alphaX86** [comment]
Use `make` to install gems and then serve the site (on Linux/macOS) For Windows, use `bundle exec jekyll serve`

**Comment by alphaX86** [comment]
Let the branch be active and I'll close the PR. In meantime just explore the site and do changes until next week Wed :)

**Comment by amino19** [comment]
@alphaX86 : Or can't we merge this PR & do the changes there!
Basically let contributors indulge in this repo.. :slightly_smiling_face: 

Also, there's not need to make a new repo. for site, cz, we can delete or clean-up all the stuff here! (_if needed_)

**Comment by alphaX86** [comment]
Agreed

**Review by amino19 — APPROVED** [review]
@alphaX86 : LGTM { My Lord } :partying_face:

**Pull request merged**
