### PR TITLE
feat: Add Gitpod and improve `README.md`

### PR DESCRIPTION
**Pull request by Panquesito7**
**Description**

- Add the [Gitpod Ready-to-Code](https://gitpod.io/#https://github.com/devstrons/hello-world) service and improve `README.md`.

**Notes for Reviewers:**

Ready to merge.

**[Signed commits](https://github.com/DevsTrons/hello-world/blob/master/CONTRIBUTING.md)**

- [x] Yes, I am a Member of **DEVSTRONS'**

### CODE REVIEW

**Comment by amino19** [comment]
@Panquesito7: Need to discuss this stuff, at voice channel with @vsnthdev! : )

**Comment by Panquesito7** [comment]
> @Panquesito7: Need to discuss this stuff, at voice channel with @vsnthdev! : )

Alright. Let me know when do you want to discuss about this. 🙂

**Comment by amino19** [comment]
> > @Panquesito7: Need to discuss this stuff, at voice channel with @vsnthdev! : )
> 
> Alright. Let me know when do you want to discuss about this. slightly_smiling_face

Thanks for asking, you can subscribe to our calendar from [here](https://tinyurl.com/DevstronsCalendar).
_More specific: Tomorrow (9th Sep.), we're gonna shoot our project discussion again!_

**Comment by amino19** [comment]
@Panquesito7: Thanks for your contribution! :smiley:

**Pull request merged**
